package com.shinkson47.SplashX6.game.units

/**
 * # Types of units available.
 * Names match the title of the corresponding sprite
 * @author [Jordan T. Gray](https://www.shinkson47.in) on 02/06/2021
 * @since PRE-ALPHA 0.0.1
 * @version 1
 */
enum class UnitClass {
    _BASE,
    settler,
    aegiscruiser,
    alpinetroop,
    archers,
    artillery,
    awacs,
    battleship,
    bomber,
    cannon,
    caravan,
    caravel,
    carrier,
    catapult,
    cavalry,
    chariot,
    cruiser,
    crusaders,
    destroyer,
    diplomat,
    dragoon,
    elepants,
    engineers,
    explorer,
    fanatics,
    fighter,
    freight,
    frigate,
    galleon,
    helicopter,
    horsemen,
    howitzer,
    ironclad,
    knights,
    legion,
    marines,
    mechinfantry,
    missile,
    musketeers,
    nuke,
    paratrooper,
    partisan,
    phalanx,
    pikemen,
    riflemen,
    spy,
    stealthbomber,
    stealthfighter,
    submarine,
    tank,
    transport,
    trireme,
    warrior,
    worker,
}