# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle



# ====================================================================================================================================================================================
#
#  /$$$$$$$  /$$$$$$$$ /$$       /$$$$$$$$  /$$$$$$   /$$$$$$  /$$$$$$$$        /$$$$$$  /$$   /$$ /$$$$$$$$  /$$$$$$  /$$   /$$       /$$$$$$$  /$$   /$$ /$$$$$$ /$$       /$$$$$$$ 
# | $$__  $$| $$_____/| $$      | $$_____/ /$$__  $$ /$$__  $$| $$_____/       /$$__  $$| $$  | $$| $$_____/ /$$__  $$| $$  /$$/      | $$__  $$| $$  | $$|_  $$_/| $$      | $$__  $$
# | $$  \ $$| $$      | $$      | $$      | $$  \ $$| $$  \__/| $$            | $$  \__/| $$  | $$| $$      | $$  \__/| $$ /$$/       | $$  \ $$| $$  | $$  | $$  | $$      | $$  \ $$
# | $$$$$$$/| $$$$$   | $$      | $$$$$   | $$$$$$$$|  $$$$$$ | $$$$$         | $$      | $$$$$$$$| $$$$$   | $$      | $$$$$/        | $$$$$$$ | $$  | $$  | $$  | $$      | $$  | $$
# | $$__  $$| $$__/   | $$      | $$__/   | $$__  $$ \____  $$| $$__/         | $$      | $$__  $$| $$__/   | $$      | $$  $$        | $$__  $$| $$  | $$  | $$  | $$      | $$  | $$
# | $$  \ $$| $$      | $$      | $$      | $$  | $$ /$$  \ $$| $$            | $$    $$| $$  | $$| $$      | $$    $$| $$\  $$       | $$  \ $$| $$  | $$  | $$  | $$      | $$  | $$
# | $$  | $$| $$$$$$$$| $$$$$$$$| $$$$$$$$| $$  | $$|  $$$$$$/| $$$$$$$$      |  $$$$$$/| $$  | $$| $$$$$$$$|  $$$$$$/| $$ \  $$      | $$$$$$$/|  $$$$$$/ /$$$$$$| $$$$$$$$| $$$$$$$/
# |__/  |__/|________/|________/|________/|__/  |__/ \______/ |________/       \______/ |__/  |__/|________/ \______/ |__/  \__/      |_______/  \______/ |______/|________/|_______/ 
#
# ====================================================================================================================================================================================
#
# This build is ran with any changes appended to the master.
#
# It's intent is to check that the master is stable, buildable, and in the correct release configuration.
#
# TODO
#                                                                                                                                                                                   
# Unit tests : 
#   Check for missing language strings
#   Check for debug mode
#   Check for disabled fullscreen                                                                                                                                                                                    

name: Release Build check

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop
      

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
  
    # Configure the JDK.
    # TODO can we cache this so we don't have to do it every time??
    # Note: We don't configure kotlin. Gradle will handle that.
    # However, we need java to run gradle.
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'

    - name: Clone Splash X6
      uses: actions/checkout@v2

    - name: Restore cached build output
      uses: actions/cache@v2
      with:
       path: |
         ~/.gradle/caches
         ~/.gradle/wrapper
         ~/build
         ~/core/build
         ~/desktop/build
       key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
       restore-keys: |
         ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradle wrapper
      run: chmod +x gradlew

    - name: Build Splash X6 using Gradle
      run: ./gradlew desktop:dist
      
    - name: Upload resulting .jar
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Splash X6 build
        path: ./desktop/build/libs/desktop-1.0.jar

    - name: Run internal tests
      run: java -jar ./desktop/build/libs/desktop-1.0.jar butt # Build Unit Test Trigger ;)
      # TODO i have no fucking clue how to check the exit code. It won't be 0, even when is's successful cause of some gradle bullshittery. Hmm.
